version: '1.1'

services:

  prometheus:
    image: prom/prometheus:v2.44.0
    user: root
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/conf:/etc/prometheus
    extra_hosts:
      host.docker.internal: 10.0.2.2

  grafana:
    image: grafana/grafana:9.5.2
    user: root
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  zookeeper-1:
    image: my-own-kafka
    ports:
      - "2181:2181"
    environment:
      - SPRING_PROFILES_ACTIVE=zookeeper
      - SERVER_PORT=2181
      - SERVER_ADDRESS=zookeeper-1
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
      - KAFKA_ZOOKEEPER_SLAVE=false
    volumes:
      - ./data/zookeeper-1/:/app/data
      - ./application-zookeeper.properties:/app/application-zookeeper.properties
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST -f http://zookeeper-1:2181/zookeeper/health"]
      start_period: 50s
      interval: 3s
      timeout: 1s
      retries: 5

  zookeeper-2:
    image: my-own-kafka
    ports:
      - "2182:2182"
    environment:
      - SPRING_PROFILES_ACTIVE=zookeeper
      - SERVER_PORT=2182
      - SERVER_ADDRESS=zookeeper-2
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-2:2182
      - KAFKA_ZOOKEEPER_MASTER=false
    volumes:
      - ./data/zookeeper-2/:/app/data
      - ./application-zookeeper.properties:/app/application-zookeeper.properties
    networks:
      - public
    depends_on:
      zookeeper-1:
        condition: service_healthy


  broker-1:
    image: my-own-kafka
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8081
      - SERVER_ADDRESS=broker-1
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-1:/app/data
      - ./application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      zookeeper-1:
        condition: service_healthy

  broker-2:
    image: my-own-kafka
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8082
      - SERVER_ADDRESS=broker-2
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-2:/app/data
      - ./application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      zookeeper-1:
        condition: service_healthy

  broker-3:
    image: my-own-kafka
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8083
      - SERVER_ADDRESS=broker-3
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-3:/app/data
      - ./application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      zookeeper-1:
        condition: service_healthy

networks:
  public:
