version: '1.1'

services:
  zookeeper-1:
    image: my-own-kafka
    ports:
      - "2181:2181"
    environment:
      - SPRING_PROFILES_ACTIVE=zookeeper
      - SERVER_PORT=2181
      - SERVER_ADDRESS=zookeeper-1
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/zookeeper-1/:/app/data
      - ./src/main/resources/application-zookeeper.properties:/app/application-zookeeper.properties
    networks:
      - public
    healthcheck:
      test: "exit 0"
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 5


  broker-1:
    image: my-own-kafka
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8081
      - SERVER_ADDRESS=broker-1
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-1:/app/data
      - ./src/main/resources/application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      zookeeper-1:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 5

  broker-2:
    image: my-own-kafka
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8082
      - SERVER_ADDRESS=broker-2
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-2:/app/data
      - ./src/main/resources/application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      broker-1:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 5

  broker-3:
    image: my-own-kafka
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=broker
      - SERVER_PORT=8083
      - SERVER_ADDRESS=broker-3
      - KAFKA_ZOOKEEPER_CONNECT_URL=http://zookeeper-1:2181
    volumes:
      - ./data/broker-3:/app/data
      - ./src/main/resources/application-broker.properties:/app/application-broker.properties
    networks:
      - public
    depends_on:
      broker-2:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 5

networks:
  public:
