global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - localhost:9100
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        regex: '(.*):9100'
        replacement: '${1}'

  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['zookeeper-1:2181', 'zookeeper-2:2182', 'broker-1:8081', 'broker-2:8082', 'broker-3:8083', 'node-exporter:9100']
        labels:
          application: 'My Spring Boot Application'