# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI with Maven and SCP
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean maven
        run: mvn clean

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

#      - name: Clear last files
#        run: sudo rm -rf /home/gituser/custom-kafka && mkdir /home/gituser/custom-kafka && mkdir /home/gituser/custom-kafka/target

      - name: Move files to dest directory
        run: mv target/*.jar /home/gituser/custom-kafka/target/application.jar && mv docker-compose.yml /home/gituser/custom-kafka/docker-compose.yml && mv Dockerfile /home/gituser/custom-kafka/Dockerfile && mv src/main/resources/application-zookeeper.properties /home/gituser/custom-kafka/application-zookeeper.properties && mv src/main/resources/application-broker.properties /home/gituser/custom-kafka/application-broker.properties

      - name: cd to dest directory
        run: cd /home/gituser/custom-kafka

      - name: build docker image
        run: cd /home/gituser/custom-kafka && docker build -t my-own-kafka .

      - name: docker compose down
        run: cd /home/gituser/custom-kafka && docker compose down

      - name: docker compose up
        run: cd /home/gituser/custom-kafka && docker compose up -d

